import Head from "next/head";

const LandingPage = () => {
  return (
    <>
      <Head>
        <title>Home | Kopi Kita</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        
      </main>
    </>
  );
};

export default LandingPage;
